import speaker from "./images/speaker.jpeg";
import boat3w from "./images/boat3w.jpeg";
import boat5w from "./images/boat5w.jpeg";
import CasualPuffSleeveSolid from "./images/CasualPuffSleeveSolid.jpeg";
import CuffedSleeveSolidWomenWhiteTop from "./images/CuffedSleeveSolidWomenWhiteTop.jpeg";
import iphone11 from "./images/iphone11.jpeg";
import jblspeaker from "./images/jblspeaker.jpeg";
import kedarFabAnarakali from "./images/kedarFabAnarakali.jpeg";
// import laptopposter from "./images/laptopposter.jpeg";
import MenSolidFormalSlimShirt from "./images/MenSolidFormalSlimShirt.jpeg";
import MenStripedCasualMandarinShirt from "./images/MenStripedCasualMandarinShirt.jpeg";
import motorolaG8PowerLite from "./images/motorolaG8PowerLite.jpeg";
// import rakiposter from "./images/rakiposter.jpeg";
import RegularFitMenBeigeCottonLycraBlendtrousers from "./images/RegularFitMenBeigeCottonLycraBlendtrousers.jpeg";
// import saleposter from "./images/saleposter.jpeg";
import samsungGalaxyS20Ultra from "./images/samsungGalaxyS20Ultra.jpeg";
import shreeImplexEmboroidered from "./images/shreeImplexEmboroidered.jpeg";
import SolidMenMandarinCollarWhiteBlackTShirt from "./images/SolidMenMandarinCollarWhiteBlackTShirt.jpeg";
import vivoV17Pro from "./images/vivoV17Pro.jpeg";
import AsusVivoBook15Ryzen5QuadCore from "./images/AsusVivoBook15Ryzen5QuadCore.jpeg";
import DrogoMRunningShoeForMen from "./images/DrogoMRunningShoeForMen.jpeg";

export const ITEMS = [
  {
    id: 0,
    name: "Mivi Zero..",
    fullName: "Mivi Zero Portable Bluetooth Speaker  (Black, Mono Channel)",
    image: speaker,
    category: "speakers",
    rating: 4.6,
    warranty: true,
    warrantyDuration: "1 Year",
    colors: ["black"],
    trending: true,
    height: 150,
    width: 100,
    price: "899",
    originalPrice: "4000",
    description:
      "Breathe life into your party with this Mivi Zero Bluetooth speaker. With its 800 mAh battery and Bluetooth connectivity, this speaker ensures a wireless listening experience. Also, its compact and lightweight design lets you carry it anywhere you go.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 1,
    name: "JBL Go PLUS",
    fullName: "JBL Go PLUS Portable Bluetooth Speaker  (Black, Mono Channel)",
    image: jblspeaker,
    category: "speakers",
    rating: 4.3,
    warranty: true,
    warrantyDuration: "1 Year",
    colors: ["black", "blue", "red"],
    trending: false,
    height: 150,
    width: 100,
    price: "1,599",
    originalPrice: "2,799",
    description:
      "With this speaker from JBL, you can breathe life into your party with the legendary JBL Signature Sound. Thanks to its One-touch Button and Noise-cancelling Speakerphone, you can talk to your loved ones seamlessly.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 2,
    name: "boAt Stone..",
    fullName:
      "boAt Stone230 3 W Bluetooth Speaker  (Charcoal Black, Mono Channel)",
    image: boat3w,
    category: "speakers",
    rating: 4.3,
    warranty: true,
    warrantyDuration: "1 Year",
    colors: ["Charcoal Black", "Midnight blue"],
    trending: false,
    height: 150,
    width: 100,
    price: "999",
    originalPrice: "2,999",
    description:
      "Sales Packag boAt Stone 230 Model Number Stone230 Type Mobile/Tablet Speaker Bluetooth Yes Memory Card Slot Yes",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 3,
    name: "boAt Stone..",
    fullName: "boAt Stone 300 5 W Bluetooth Speaker  (Red, Mono Channel)",
    image: boat5w,
    category: "speakers",
    rating: 4.3,
    warranty: true,
    warrantyDuration: "1 Year",
    colors: ["Black", "blue", "red"],
    trending: false,
    height: 150,
    width: 100,
    price: "1,299",
    originalPrice: "3,499",
    description:
      "The ever friendly pocket buddy of music has just bounced onto the scene, fresh from the factories of Nirvana. Revel in the Immersive Sound of the boAt Stone 300, power packed with a 50mm driver and 1500mAh Rechargeable Lithium Battery. The deal is, high-quality audio for up to 6 hours at a time anytime, anyplace with IPX 7 Water Proof and a Shock Resistant Design. Provided with the latest style finish and materials, stay a step ahead of the style and audio world, in 3 different colours. Plug into music with Bluetooth (V5.0) or Aux mode and enjoy the sweet waves of Nirvana. Control music seamlessly with the integrated controls and even handle incoming calls with ease via the inbuilt-mic. Whether itÃ¢ÂÂs internal or external, get ready to Battle The Elements with the boAt Stone 300.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 4,
    name: "Samsung Ga..",
    fullName: "Samsung Galaxy S20 Ultra (Cosmic Gray, 128 GB)  (12 GB RAM)",
    image: samsungGalaxyS20Ultra,
    category: "mobiles",
    rating: 4.1,
    warranty: true,
    warrantyDuration: "1 Year",
    colors: ["Black"],
    trending: true,
    height: 150,
    width: 100,
    price: "97,999",
    originalPrice: "1,03,000",
    description:
      "Say hello to the powerful and stylish Samsung Galaxy S20 Ultra smartphone. Featuring a 108 MP high-resolution camera with 100X Zoom, you can capture stunning photos like never before on this smartphone. It also comes with a long-lasting 5000 mAh battery so you can stay entertained for a long time. That's not all, the Samsung Galaxy S20 Ultra comes with the Infinity-O display and a seamless design, which makes it a must-have for all the gadget-enthusiasts.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 5,
    name: "Vivo V17Pro",
    fullName: "Vivo V17Pro (Midnight Ocean Black, 128 GB)  (8 GB RAM)",
    image: vivoV17Pro,
    category: "mobiles",
    rating: 4.5,
    warranty: true,
    warrantyDuration: "1 Year",
    colors: ["white", "Black"],
    trending: false,
    height: 150,
    width: 100,
    price: "29,499",
    originalPrice: "32,990",
    description:
      "Handset, Earphone, User Manual, Type-C to USB Cable, USB Power Adapter, Sim Ejector Pin, Protective Case, Protective Film(Applied)I purchased vivo v 17 pro last month, after one month phone has blasted automatically, I approached vivo service center and they helped us and with in 10 days they return another phon, company is so so good thanku VIVO and the phone was excellent superb mind blowing amazing product",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 6,
    name: "iPhone 11",
    fullName: "Apple iPhone 11 (Purple, 128 GB)",
    image: iphone11,
    category: "mobiles",
    rating: 4.7,
    warranty: true,
    warrantyDuration: "1 Year",
    colors: ["Black", "Green", "Purple"],
    trending: false,
    height: 150,
    width: 100,
    price: "73,600",
    originalPrice: "73,600",
    description:
      "Featuring a 15.49-cm (6.1) all-screen Liquid Retina LCD and a glass and aluminum design, the iPhone 11 is as beautiful as it gets. Also, the IP68 rating ensures that is water-resistant up to 2 meters for 30 minutes.The iPhone 11 features dual 12 MP Ultra Wide (13mm) and Wide (26mm) cameras with 4K video recording up to 60 fps. The Ultra Wide camera provides 120° field of view, letting you capture four times more scene, and the Wide camera provides 100% Focus Pixels for up to three times faster autofocus in low light",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 7,
    name: "Motorola G8",
    fullName: "Motorola G8 Power Lite (Royal Blue, 64 GB)  (4 GB RAM)",
    image: motorolaG8PowerLite,
    category: "mobiles",
    rating: 4.4,
    warranty: true,
    warrantyDuration: "1 Year",
    colors: ["Arctic Blue", "Royal Blue"],
    trending: false,
    height: 150,
    width: 100,
    price: "9,499",
    originalPrice: "9,999",
    description:
      "The G8 Power Lite smartphone from Motorola takes advantage of a 2.3 GHz octa-core processor and about 4 GB of RAM to offer you lag-free smartphone performance. This phone even has a 5000-mAh battery that delivers a runtime of up to 2 days once it is fully charged, so you can make the most of its 16.51-centimetre (6.5) Max Vision HD+ display by watching movies, playing games, and much more.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 8,
    name: "Embroidered..",
    fullName: "Embroidered Silk Blend Semi Stitched Anarkali Gown  (Dark Blue)",
    image: kedarFabAnarakali,
    category: "women",
    rating: 3.9,
    warranty: false,
    warrantyDuration: "0",
    colors: ["Black", "Dark Blue", "Dark Green", "Maroon", "Purple", "Yellow"],
    trending: false,
    height: 150,
    width: 100,
    price: "1,099",
    originalPrice: "5,999",
    description:
      "Embroidered Silk Blend Semi Stitched Anarkali Gown broidered Silk Blend Semi Stitched Anarkali Gown idered Silk Blend Semi Stitched Anarkali Gown mbroidered Silk Blend Semi Stitched Anarkali Gown.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 9,
    name: "Embroidered Se..",
    fullName: "Embroidered Semi Stitched Lehenga Choli  (Maroon)",
    image: shreeImplexEmboroidered,
    category: "women",
    rating: 3.9,
    warranty: false,
    warrantyDuration: "0",
    colors: ["Black", "Dark Blue", "Dark Green", "Maroon", "Purple", "Yellow"],
    trending: false,
    height: 150,
    width: 100,
    price: "999",
    originalPrice: "5,999",
    description:
      "Embroidered Silk Blend Semi Stitched Anarkali Gown broidered Silk Blend Semi Stitched Anarkali Gown idered Silk Blend Semi Stitched Anarkali Gown mbroidered Silk Blend Semi Stitched Anarkali Gown.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 10,
    name: "Casual Puff..",
    fullName: "Casual Puff Sleeve Solid Women Maroon Top",
    image: CasualPuffSleeveSolid,
    category: "women",
    rating: 4.1,
    warranty: false,
    warrantyDuration: "0",
    colors: ["Black", "Dark Blue", "Dark Green", "Maroon", "Yellow"],
    trending: false,
    height: 150,
    width: 100,
    price: "355",
    originalPrice: "1,399",
    description:
      "Embroidered Silk Blend Semi Stitched Anarkali Gown broidered Silk Blend Semi Stitched Anarkali Gown idered Silk Blend Semi Stitched Anarkali Gown mbroidered Silk Blend Semi Stitched Anarkali Gown.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 11,
    name: "Casual Cuff..",
    fullName: "Casual Cuffed Sleeve Solid Women White Top",
    image: CuffedSleeveSolidWomenWhiteTop,
    category: "women",
    rating: 4.0,
    warranty: false,
    warrantyDuration: "0",
    colors: ["Black", "Dark Blue", "Dark Green", "Yellow"],
    trending: true,
    height: 150,
    width: 100,
    price: "449",
    originalPrice: "899",
    description:
      "Embroidered Silk Blend Semi Stitched Anarkali Gown broidered Silk Blend Semi Stitched Anarkali Gown idered Silk Blend Semi Stitched Anarkali Gown mbroidered Silk Blend Semi Stitched Anarkali Gown.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 12,
    name: "Solid Men..",
    fullName: "Solid Men Mandarin Collar White, Black T-Shirt",
    image: SolidMenMandarinCollarWhiteBlackTShirt,
    category: "men",
    rating: 4.0,
    warranty: false,
    warrantyDuration: "0",
    colors: ["Black", "Dark Blue", "Dark Green", "Yellow"],
    trending: true,
    height: 150,
    width: 100,
    price: "341",
    originalPrice: "1,999",
    description:
      "Embroidered Silk Blend Semi Stitched Anarkali Gown broidered Silk Blend Semi Stitched Anarkali Gown idered Silk Blend Semi Stitched Anarkali Gown mbroidered Silk Blend Semi Stitched Anarkali Gown.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 13,
    name: "Men Striped..",
    fullName: "Men Striped Casual Mandarin Shirt",
    image: MenStripedCasualMandarinShirt,
    category: "men",
    rating: 3.8,
    warranty: false,
    warrantyDuration: "0",
    colors: ["Black", "Dark Blue", "Dark Green", "Yellow"],
    trending: false,
    height: 150,
    width: 100,
    price: "567",
    originalPrice: "1,499",
    description:
      "Embroidered Silk Blend Semi Stitched Anarkali Gown broidered Silk Blend Semi Stitched Anarkali Gown idered Silk Blend Semi Stitched Anarkali Gown mbroidered Silk Blend Semi Stitched Anarkali Gown.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 14,
    name: "Men Solid..",
    fullName: "Men Solid Formal Slim Shirt",
    image: MenSolidFormalSlimShirt,
    category: "men",
    rating: 4.0,
    warranty: false,
    warrantyDuration: "0",
    colors: ["Black", "Dark Blue", "Dark Green", "Yellow"],
    trending: false,
    height: 150,
    width: 100,
    price: "560",
    originalPrice: "1,199",
    description:
      "Embroidered Silk Blend Semi Stitched Anarkali Gown broidered Silk Blend Semi Stitched Anarkali Gown idered Silk Blend Semi Stitched Anarkali Gown mbroidered Silk Blend Semi Stitched Anarkali Gown.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 15,
    name: "Regular Fit..",
    fullName: "Regular Fit Men Beige Cotton Lycra Blend Trousers",
    image: RegularFitMenBeigeCottonLycraBlendtrousers,
    category: "men",
    rating: 4.0,
    warranty: false,
    warrantyDuration: "0",
    colors: ["Black", "Dark Blue", "Dark Green", "Yellow"],
    trending: false,
    height: 150,
    width: 100,
    price: "845",
    originalPrice: "1,999",
    description:
      "Embroidered Silk Blend Semi Stitched Anarkali Gown broidered Silk Blend Semi Stitched Anarkali Gown idered Silk Blend Semi Stitched Anarkali Gown mbroidered Silk Blend Semi Stitched Anarkali Gown.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 16,
    name: "Drogo M..",
    fullName: "Drogo M Running Shoe For Men  (Navy)",
    image: DrogoMRunningShoeForMen,
    category: "shoes",
    rating: 4.2,
    warranty: true,
    warrantyDuration: "90 days",
    colors: ["Black", "Dark Blue", "Dark Green", "Yellow"],
    trending: true,
    height: 140,
    width: 120,
    price: "1,479",
    originalPrice: "2,699",
    description:
      "Embroidered Silk Blend Semi Stitched Anarkali Gown broidered Silk Blend Semi Stitched Anarkali Gown idered Silk Blend Semi Stitched Anarkali Gown mbroidered Silk Blend Semi Stitched Anarkali Gown.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 17,
    name: "Asus VivoBook 15",
    fullName:
      "Asus VivoBook 15 Ryzen 5 Quad Core - (8 GB/1 TB HDD/256 GB SSD/Windows 10 Home) X512DA-EJ1298TS Thin and Light Laptop  (15.6 inch, Peacock Blue, 1.68 kg)",
    image: AsusVivoBook15Ryzen5QuadCore,
    category: "laptop",
    rating: 4.2,
    warranty: true,
    warrantyDuration: "1 year",
    colors: ["Black", "Dark Blue"],
    trending: true,
    height: 140,
    width: 120,
    price: "47,990",
    originalPrice: "49,151",
    description:
      "Embroidered Silk Blend Semi Stitched Anarkali Gown broidered Silk Blend Semi Stitched Anarkali Gown idered Silk Blend Semi Stitched Anarkali Gown mbroidered Silk Blend Semi Stitched Anarkali Gown.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
];
