export const ITEMS = [
  {
    id: 0,
    name: "Mivi Zero Portable Bluetooth Speaker",
    fullName: "Mivi Zero Portable Bluetooth Speaker  (Black, Mono Channel)",
    image: "./images/speaker.jpeg",
    category: "speakers",
    rating: 4.6,
    warranty: true,
    warrantyDuration: "1 Year",
    colors: ["black"],
    tranding: true,
    price: "899",
    originalPrice: "4000",
    description:
      "Breathe life into your party with this Mivi Zero Bluetooth speaker. With its 800 mAh battery and Bluetooth connectivity, this speaker ensures a wireless listening experience. Also, its compact and lightweight design lets you carry it anywhere you go.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 1,
    name: "JBL Go PLUS Portable Bluetooth Speaker",
    fullName: "JBL Go PLUS Portable Bluetooth Speaker  (Black, Mono Channel)",
    image: "./images/jblspeaker.jpeg",
    category: "speakers",
    rating: 4.3,
    warranty: true,
    warrantyDuration: "1 Year",
    colors: ["black", "blue", "red"],
    tranding: false,
    price: "1,599",
    originalPrice: "2,799",
    description:
      "With this speaker from JBL, you can breathe life into your party with the legendary JBL Signature Sound. Thanks to its One-touch Button and Noise-cancelling Speakerphone, you can talk to your loved ones seamlessly.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 2,
    name: "boAt Stone230 3 W Bluetooth Speaker",
    fullName:
      "boAt Stone230 3 W Bluetooth Speaker  (Charcoal Black, Mono Channel)",
    image: "./images/boat3w.jpeg",
    category: "speakers",
    rating: 4.3,
    warranty: true,
    warrantyDuration: "1 Year",
    colors: ["Charcoal Black", "Midnight blue"],
    tranding: false,
    price: "999",
    originalPrice: "2,999",
    description:
      "Sales Packag boAt Stone 230 Model Number Stone230 Type Mobile/Tablet Speaker Bluetooth Yes Memory Card Slot Yes",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
  {
    id: 3,
    name: "boAt Stone 300 5 W Bluetooth Speaker",
    fullName: "boAt Stone 300 5 W Bluetooth Speaker  (Red, Mono Channel)",
    image: "./images/boat5w.jpeg",
    category: "speakers",
    rating: 4.3,
    warranty: true,
    warrantyDuration: "1 Year",
    colors: ["Black", "blue", "red"],
    tranding: false,
    price: "1,299",
    originalPrice: "3,499",
    description:
      "The ever friendly pocket buddy of music has just bounced onto the scene, fresh from the factories of Nirvana. Revel in the Immersive Sound of the boAt Stone 300, power packed with a 50mm driver and 1500mAh Rechargeable Lithium Battery. The deal is, high-quality audio for up to 6 hours at a time anytime, anyplace with IPX 7 Water Proof and a Shock Resistant Design. Provided with the latest style finish and materials, stay a step ahead of the style and audio world, in 3 different colours. Plug into music with Bluetooth (V5.0) or Aux mode and enjoy the sweet waves of Nirvana. Control music seamlessly with the integrated controls and even handle incoming calls with ease via the inbuilt-mic. Whether itÃ¢ÂÂs internal or external, get ready to Battle The Elements with the boAt Stone 300.",
    comments: [
      {
        id: 0,
        rating: 5,
        comment: "Imagine all the eatables, living in conFusion!",
        author: "John Lemon",
        date: "2012-10-16T17:57:28.556094Z",
      },
      {
        id: 1,
        rating: 4,
        comment:
          "Sends anyone to heaven, I wish I could get my mother-in-law to eat it!",
        author: "Paul McVites",
        date: "2014-09-05T17:57:28.556094Z",
      },
      {
        id: 2,
        rating: 3,
        comment: "Eat it, just eat it!",
        author: "Michael Jaikishan",
        date: "2015-02-13T17:57:28.556094Z",
      },
      {
        id: 3,
        rating: 4,
        comment: "Ultimate, Reaching for the stars!",
        author: "Ringo Starry",
        date: "2013-12-02T17:57:28.556094Z",
      },
      {
        id: 4,
        rating: 2,
        comment: "It's your birthday, we're gonna party!",
        author: "25 Cent",
        date: "2011-12-02T17:57:28.556094Z",
      },
    ],
  },
];
